EJ2-Documentation-849998-Ug-Documentation-For-Caption-Template
syncfusion-content/ej2-grid-docs pull request #176
Opened 2023-12-22 11:19 UTC by harinikrh

2023-12-22 11:20 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-Caption-Template-849998-JS-TS](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/430/console)**

2023-12-22 11:38 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Caption-Template-849998-JS-TS](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/430/console)**

2023-12-22 11:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Caption-Template-849998-JS-TS](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/430/)<br/>**

2023-12-26 06:52 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-Caption-Template-849998-JS-TS](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/433/console)**

2023-12-26 06:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Caption-Template-849998-JS-TS](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/433/console)**

2023-12-26 06:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Caption-Template-849998-JS-TS](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/433/)<br/>**

2023-12-26 09:16 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Caption-Template-849998-JS-TS](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/434/console)**

2023-12-26 09:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Caption-Template-849998-JS-TS](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/434/)<br/>**

2024-01-16 09:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Caption-Template-849998-JS-TS](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/76/console)**

2024-01-16 09:14 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Caption-Template-849998-JS-TS](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/76/)<br/>**

2024-01-29 07:16 UTC, VigneshNatarajan27 requested changes
Reviewed the content. Below are my suggestion. 

1. Use the same template name as in angular (groupcaptionsettingstemplate)
2. same id name value for custom componet  in group caption.

2024-01-29 08:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Caption-Template-849998-JS-TS](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/112/console)**

2024-01-29 08:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Caption-Template-849998-JS-TS](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/112/)<br/>**

2024-01-30 11:54 UTC, VigneshNatarajan27 approved these changes
changes are fine

2024-01-31 12:25 UTC, MaithiliyK approved these changes
changes are fine

2024-01-31 12:25 UTC, merged