EJ2-Documentation-851394-Ug-Documentation-For-Dialog-Editing
syncfusion-content/ej2-grid-docs pull request #194
Opened 2024-01-03 06:53 UTC by harinikrh

2024-01-03 06:54 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/24/console)**

2024-01-03 06:55 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/24/console)**

2024-01-03 07:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/24/)<br/>**

2024-01-03 09:16 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/25/console)**

2024-01-03 09:17 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/25/)<br/>**

2024-01-03 12:10 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/27/console)**

2024-01-03 12:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/27/console)**

2024-01-03 12:15 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/27/)<br/>**

2024-01-03 12:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/28/console)**

2024-01-03 12:30 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/28/)<br/>**

2024-01-04 07:16 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/31/console)**

2024-01-04 07:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/31/)<br/>**

2024-01-29 09:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/115/console)**

2024-01-29 09:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/115/)<br/>**

2024-01-30 05:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/118/console)**

2024-01-30 05:30 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/118/)<br/>**

2024-01-30 12:04 UTC, VigneshNatarajan27 commented on ej2-javascript/grid/editing/dialog-editing.md
> +
use ShowCloseIcon property of dialog in actioncompelte event. also modify in the sample too.

2024-01-30 12:13 UTC, VigneshNatarajan27 requested changes
changes proposed

2024-01-31 05:07 UTC, harinikrh commented on ej2-javascript/grid/editing/dialog-editing.md
> +
modified the sample by using the showCloseIcon property

2024-01-31 12:33 UTC, VigneshNatarajan27 approved these changes
changes are fine

2024-01-31 12:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/129/console)**

2024-01-31 12:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Dialog-Editing-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/129/)<br/>**

2024-01-31 12:43 UTC, merged