EJ2-Documentation-853041-Ug-Documentation-For-Row-Selection
syncfusion-content/ej2-grid-docs pull request #265
Opened 2024-02-05 09:14 UTC by harinikrh

2024-02-05 09:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/148/console)**

2024-02-05 09:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/148/)<br/>**

2024-02-06 06:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/151/console)**

2024-02-06 06:19 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/151/)<br/>**

2024-02-06 11:30 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/154/console)**

2024-02-06 11:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/154/)<br/>**

2024-02-13 11:14 UTC, VigneshNatarajan27 requested changes
selectColumns API links is provided instead of selectRows API link


Select grid rows based on certain conditions topic, Javascript platform name is not properly displayed

2024-02-13 13:14 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/184/console)**

2024-02-13 13:27 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/184/console)**

2024-02-13 13:28 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/184/)<br/>**

2024-02-14 04:34 UTC, harinikrh commented
> selectColumns API links is provided instead of selectRows API link
> 
> Select grid rows based on certain conditions topic, Javascript platform name is not properly displayed

Changed the API link for selectRows
Changed in to platform name

2024-02-14 04:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/185/console)**

2024-02-14 04:39 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/185/)<br/>**

2024-02-14 04:51 UTC, VigneshNatarajan27 requested changes
persistSelection spelling is wrong

2024-02-14 06:49 UTC, MaithiliyK commented on ej2-javascript/code-snippet/grid/grid-cs184/index.js
> +var mod;
always I insist to provide meaningful name

2024-02-14 06:56 UTC, MaithiliyK reviewed
address my review comments

2024-02-14 06:56 UTC, MaithiliyK commented on ej2-javascript/code-snippet/grid/grid-cs184/index.js
> +      grid.selectRow.mod;
is this code is correct. grid.SelectRow.mod is not a proper code check on it

2024-02-14 06:56 UTC, MaithiliyK commented on ej2-javascript/code-snippet/grid/grid-cs185/index.js
> +var enableSelection = false;
is this variable needed here

2024-02-14 06:56 UTC, MaithiliyK commented on ej2-javascript/code-snippet/grid/grid-cs185/index.ts
> +let enableSelection = false;
is the variable needed here

2024-02-14 07:09 UTC, harinikrh commented on ej2-javascript/code-snippet/grid/grid-cs184/index.js
> +      grid.selectRow.mod;
changed in to grid.SelectRow(mod)

2024-02-14 07:09 UTC, harinikrh commented on ej2-javascript/code-snippet/grid/grid-cs185/index.js
> +var enableSelection = false;
Removed the variable

2024-02-14 07:11 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/190/console)**

2024-02-14 07:14 UTC, harinikrh commented on ej2-javascript/code-snippet/grid/grid-cs185/index.ts
> +let enableSelection = false;
Removed the variable

2024-02-14 07:18 UTC, VigneshNatarajan27 approved these changes
changes are fine

2024-02-14 07:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/190/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/190/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/190/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/190/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/190/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/190/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/190/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/190/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/190/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-02-14 07:24 UTC, harinikrh commented on ej2-javascript/code-snippet/grid/grid-cs184/index.js
> +var mod;
changed the variable name

2024-02-14 08:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/191/console)**

2024-02-14 08:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-grid-Row-Selection](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/191/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/191/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/191/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/191/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/191/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/191/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/191/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/191/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/191/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-02-15 11:17 UTC, MaithiliyK approved these changes
changes are fine

2024-02-15 11:17 UTC, merged

2024-02-23 04:17 UTC, VigneshNatarajan27 reviewed
changes are fine. since it is duplicate of already reviewed PR