EJ2-Documentation-851726-Ug-Documentation-For-Selection
syncfusion-content/ej2-grid-docs pull request #271
Opened 2024-02-07 07:15 UTC by harinikrh

2024-02-07 07:16 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Grid-Selection-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/156/console)**

2024-02-07 07:17 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Grid-Selection-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/156/)<br/>**

2024-02-13 10:59 UTC, VigneshNatarajan27 requested changes
highlight clearColumnSelection method and link it to API documentation.

2024-02-13 12:03 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-Grid-Selection-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/180/console)**

2024-02-13 12:05 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [EJ2-Grid-Selection-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/180/)<br/>**

2024-02-13 12:14 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Grid-Selection-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/181/console)**

2024-02-13 12:16 UTC, harinikrh commented
> highlight clearColumnSelection method and link it to API documentation.

Linked the API

2024-02-13 12:17 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Grid-Selection-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/181/)<br/>**

2024-02-14 04:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Grid-Selection-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/186/console)**

2024-02-14 04:48 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Grid-Selection-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/186/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/186/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/186/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/186/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/186/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/186/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/186/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/186/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/186/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-02-14 06:38 UTC, MaithiliyK commented on ej2-javascript/code-snippet/grid/Selection-grid-toggle/index.js
> +var enableToggleSelection = true;
what is the use of defining this variable here. Its value is not changed anywhere in the sample. Is it needed?

2024-02-14 06:39 UTC, MaithiliyK commented on ej2-javascript/code-snippet/grid/Selection-grid-toggle/index.js
> +  change: toggleColumnSelection,
in change event itself you can get the argument regarding the checked status?

2024-02-14 06:44 UTC, MaithiliyK reviewed
address my review comments

2024-02-14 06:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-Grid-Selection-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/188/console)**

2024-02-14 06:51 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-Grid-Selection-js-ts](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/188/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/188/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/188/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/188/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/188/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/188/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/188/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/188/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-grid-docs/188/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-02-14 07:51 UTC, merged