Doc(848333): Need to add the detail template exporting sample in UG of all platforms
syncfusion-content/ej2-grid-docs pull request #49
Opened 2023-09-19 14:22 UTC by rajapandiyan-settu

Added detail template exporting topic in PDF and Excel exporting of grid component.

2023-09-19 14:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/91/console)**

2023-09-19 14:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/91/)<br/>**

2023-09-20 04:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/92/console)**

2023-09-20 04:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/92/)<br/>**

2023-09-20 05:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/93/console)**

2023-09-20 05:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/93/)<br/>**

2023-09-20 06:28 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/94/console)**

2023-09-20 06:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/94/console)**

2023-09-20 06:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/94/)<br/>**

2023-09-20 06:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/95/)<br/>**

2023-09-20 09:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/97/console)**

2023-09-20 09:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/97/)<br/>**

2023-09-20 10:07 UTC, MaithiliyK commented on ej2-javascript/grid/excel-export/exporting-detail-template-grid.md
> +The grid has the option to export the detail template grid to an Excel document. By default, it will use the `Expanded` as hierarchyExportMode. Change the exporting option by using the `ExcelExportPr
provide api link

2023-09-20 10:09 UTC, MaithiliyK commented on ej2-javascript/grid/excel-export/exporting-detail-template-grid.md
> +> When using [`rowSpan`](../../api/grid/detailTemplateCell/#rowspan), it's essential to provide the cell's [`index`](../../api/grid/detailTemplateCell/#index) for proper functionality.
if you give URL for APi dont give backtick

2023-09-20 10:11 UTC, MaithiliyK commented on ej2-javascript/grid/pdf-export/exporting-detail-template-grid.md
> +The grid has the option to export the detail template to a PDF document. By default, the grid will export the master grid with expanded detail rows alone. Change the exporting option by using the `Pd
The grid has an option to export the detail template to a PDF document. By default, the grid will export the parent grid with expanded detail rows alone. use this sentence for excel exporting too

2023-09-20 10:12 UTC, MaithiliyK commented on ej2-javascript/grid/ej2-typescript-grid-toc.html
> +<li><a href="/ej2-typescript/grid/pdf-export/exporting-detail-template-grid">Exporting Detail Template Grid</a></li>
create the structure like this


PDF Exporting with Templates
•	Exporting with column template
•	Exporting with detail template
•	Exporting with caption template

2023-09-20 10:13 UTC, MaithiliyK commented on ej2-javascript/grid/pdf-export/exporting-detail-template-grid.md
> +> If a value for the `columnCount` is not provided, the PDF grid's columns in the detail row will be generated based on the count of the `columnHeader`/`rows` first row's `cells`(../../api/grid/detai
content formatting is not correct

2023-09-20 10:15 UTC, MaithiliyK commented on ej2-javascript/grid/pdf-export/exporting-detail-template-grid.md
> +* The export feature for detail templates is not supported with server-side exporting.
move the limitation under server exporting

2023-09-20 15:25 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/100/)<br/>**

2023-09-20 15:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/101/console)**

2023-09-20 15:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/101/)<br/>**

2023-09-20 17:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/102/console)**

2023-09-20 17:29 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/102/)<br/>**

2023-09-21 08:03 UTC, florenceliliana requested changes
The content review is completed.

2023-09-21 08:03 UTC, florenceliliana commented on ej2-javascript/grid/pdf-export/exporting-with-templates.md
> +PDF export allows exporting Grid with caption template to a PDF document.
The PDF export feature allows for the exporting of a Grid with a caption template to a PDF document.

2023-09-21 08:03 UTC, florenceliliana commented on ej2-javascript/grid/pdf-export/exporting-with-templates.md
> +In the below sample, the customized caption text is exported to PDF by using [captionText](../../api/grid/exportGroupCaptionEventArgs/#captiontext) property in the [exportGroupCaption](../../api/grid
In the following sample, the customized caption text is exported to PDF using the [captionText](../../api/grid/exportGroupCaptionEventArgs/#captiontext) property in the [exportGroupCaption](../../api/grid/#exportgroupcaption) event.

2023-09-22 05:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/104/console)**

2023-09-22 05:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/104/)<br/>**

2023-09-22 06:14 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/106/console)**

2023-09-22 06:15 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/106/)<br/>**

2023-09-22 06:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/107/console)**

2023-09-22 06:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/107/)<br/>**

2023-09-22 09:43 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/110/console)**

2023-09-22 09:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/110/)<br/>**

2023-09-22 10:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/112/console)**

2023-09-22 10:26 UTC, MaithiliyK approved these changes
changes are fine

2023-09-22 10:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/112/)<br/>**

2023-09-22 10:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/113/console)**

2023-09-22 10:27 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Task-848333-detailtemp-expt](https://jenkins.syncfusion.com/job/Content/job/ej2-grid-docs/113/)<br/>**

2023-09-22 10:27 UTC, jmfarook7 approved these changes
fine

2023-09-22 10:28 UTC, merged